export const data = [
  {
    id: 'CHT-0907-6973-2140',
    name: 'Test Group - Vendor',
    revision: 1,
    type: 'Group',
    participants: [
      {
        id: 'CHP-8745-6195-2902',
        revision: 1,
        chat: {
          id: 'CHT-0907-6973-2140',
          name: 'Test Group - Vendor',
          revision: 1,
          type: 'Group',
        },
        contact: {
          id: 'CTT-0294-3021',
          name: 'Darren Drumm',
          revision: 1,
          email: 'darren.drumm@softwareone.com',
          identity: {
            id: 'USR-7703-9615',
            name: 'Darren Drumm',
            revision: 3,
          },
        },
        identity: {
          id: 'USR-7703-9615',
          name: 'Darren Drumm',
          revision: 3,
        },
        account: {
          id: 'ACC-4714-5418',
          name: 'Microsoft',
          revision: 1,
          type: 'Vendor',
          status: 'Active',
        },
        muted: false,
        status: 'Active',
        unreadMessageCount: 1,
      },
      {
        id: 'CHP-9901-7302-2345',
        revision: 3,
        chat: {
          id: 'CHT-0907-6973-2140',
          name: 'Test Group - Vendor',
          revision: 1,
          type: 'Group',
        },
        contact: {
          id: 'CTT-4262-4296',
          name: 'Tania Roche',
          revision: 1,
          email: 'tania.roche@softwareone.com',
          identity: {
            id: 'USR-2267-7838',
            name: 'Tania Roche',
            revision: 1,
          },
        },
        identity: {
          id: 'USR-2267-7838',
          name: 'Tania Roche',
          revision: 1,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        lastReadMessage: {
          id: 'CMG-3801-3447-8769',
          revision: 1,
          content: 'a test message with very very very long text that needs to be truncated',
          visibility: 'Public',
          isDeleted: false,
        },
        unreadMessageCount: 1000,
      },
    ],
    lastMessage: {
      id: 'CMG-3801-3447-8769',
      revision: 1,
      chat: {
        id: 'CHT-0907-6973-2140',
        name: 'Test Group - Vendor',
        revision: 1,
        type: 'Group',
      },
      sender: {
        id: 'CHP-9901-7302-2345',
        revision: 3,
        chat: {
          id: 'CHT-0907-6973-2140',
          name: 'Test Group - Vendor',
          revision: 1,
          type: 'Group',
        },
        contact: {
          id: 'CTT-4262-4296',
          name: 'Tania Roche',
          revision: 1,
          email: 'tania.roche@softwareone.com',
          identity: {
            id: 'USR-2267-7838',
            name: 'Tania Roche',
            revision: 1,
          },
        },
        identity: {
          id: 'USR-2267-7838',
          name: 'Tania Roche',
          revision: 1,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        lastReadMessage: {
          id: 'CMG-3801-3447-8769',
          revision: 1,
          content: 'a test message with very very very long text that needs to be truncated',
          visibility: 'Public',
          isDeleted: false,
        },
        unreadMessageCount: 0,
      },
      content: 'a test message with very very very long text that needs to be truncated',
      visibility: 'Public',
      isDeleted: false,
      identity: {
        id: 'USR-2267-7838',
        name: 'Tania Roche',
        revision: 1,
      },
      audit: {
        deleted: {},
        madePublic: {},
        madePrivate: {},
        created: {
          at: '2026-03-10T13:10:37.212Z',
          by: {
            id: 'USR-2267-7838',
            name: 'Tania Roche',
            revision: 1,
          },
        },
        updated: {},
      },
    },
  },
  {
    id: 'CHT-2749-6237-9222',
    revision: 1,
    type: 'Direct',
    participants: [
      {
        id: 'CHP-1501-9758-7338',
        revision: 1,
        chat: {
          id: 'CHT-2749-6237-9222',
          revision: 1,
          type: 'Direct',
        },
        contact: {
          id: 'CTT-2736-2051',
          name: 'microsoft licenses address',
          revision: 1,
          email: 'msft@medpt.com',
          identity: {
            id: 'USR-2421-6365',
            name: 'microsoft licenses address',
            revision: 1,
          },
        },
        identity: {
          id: 'USR-2421-6365',
          name: 'microsoft licenses address',
          revision: 1,
        },
        account: {
          id: 'ACC-2180-7619',
          name: 'Medpoint Digital, Inc.',
          revision: 1,
          type: 'Client',
          status: 'Active',
        },
        muted: false,
        status: 'Active',
        unreadMessageCount: 1,
      },
      {
        id: 'CHP-8024-2154-4959',
        revision: 5,
        chat: {
          id: 'CHT-2749-6237-9222',
          revision: 1,
          type: 'Direct',
        },
        contact: {
          id: 'CTT-4262-4296',
          name: 'Tania Roche',
          revision: 1,
          email: 'tania.roche@softwareone.com',
          identity: {
            id: 'USR-2267-7838',
            name: 'Tania Roche',
            revision: 1,
          },
        },
        identity: {
          id: 'USR-2267-7838',
          name: 'Tania Roche',
          revision: 1,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        lastReadMessage: {
          id: 'CMG-6449-4326-9246',
          revision: 1,
          content: 'test',
          visibility: 'Public',
          isDeleted: false,
        },
        unreadMessageCount: 2,
      },
    ],
    lastMessage: {
      id: 'CMG-6449-4326-9246',
      revision: 1,
      chat: {
        id: 'CHT-2749-6237-9222',
        revision: 1,
        type: 'Direct',
      },
      sender: {
        id: 'CHP-8024-2154-4959',
        revision: 5,
        chat: {
          id: 'CHT-2749-6237-9222',
          revision: 1,
          type: 'Direct',
        },
        contact: {
          id: 'CTT-4262-4296',
          name: 'Tania Roche',
          revision: 1,
          email: 'tania.roche@softwareone.com',
          identity: {
            id: 'USR-2267-7838',
            name: 'Tania Roche',
            revision: 1,
          },
        },
        identity: {
          id: 'USR-2267-7838',
          name: 'Tania Roche',
          revision: 1,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        lastReadMessage: {
          id: 'CMG-6449-4326-9246',
          revision: 1,
          content: 'test',
          visibility: 'Public',
          isDeleted: false,
        },
        unreadMessageCount: 0,
      },
      content: 'test',
      visibility: 'Public',
      isDeleted: false,
      identity: {
        id: 'USR-2267-7838',
        name: 'Tania Roche',
        revision: 1,
      },
      audit: {
        deleted: {},
        madePublic: {},
        madePrivate: {},
        created: {
          at: '2026-03-09T12:54:25.055Z',
          by: {
            id: 'USR-2267-7838',
            name: 'Tania Roche',
            revision: 1,
          },
        },
        updated: {},
      },
    },
  },
  {
    id: 'CHT-9231-8917-3633',
    name: 'Mobile Dev Test Chat - Group One',
    revision: 2,
    type: 'Group',
    participants: [
      {
        id: 'CHP-2317-4035-2836',
        revision: 1,
        chat: {
          id: 'CHT-9231-8917-3633',
          name: 'Mobile Dev Test Chat - Group One',
          revision: 2,
          type: 'Group',
        },
        contact: {
          id: 'CTT-0869-8652',
          name: 'Maciej Biernat',
          revision: 1,
          email: 'maciej.biernat@softwareone.com',
          identity: {
            id: 'USR-1835-2941',
            name: 'Maciej Biernat',
            icon: '/v1/accounts/users/USR-1835-2941/icon',
            revision: 8,
          },
        },
        identity: {
          id: 'USR-1835-2941',
          name: 'Maciej Biernat',
          icon: '/v1/accounts/users/USR-1835-2941/icon',
          revision: 8,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        unreadMessageCount: 6,
      },
      {
        id: 'CHP-4483-3016-2902',
        revision: 1,
        chat: {
          id: 'CHT-9231-8917-3633',
          name: 'Mobile Dev Test Chat - Group One',
          revision: 2,
          type: 'Group',
        },
        contact: {
          id: 'CTT-5259-9165',
          name: 'Halil Karaca',
          revision: 1,
          email: 'halil.karaca@softwareone.com',
          identity: {
            id: 'USR-8314-3681',
            name: 'Halil Karaca',
            revision: 1,
          },
        },
        identity: {
          id: 'USR-8314-3681',
          name: 'Halil Karaca',
          revision: 1,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        unreadMessageCount: 6,
      },
      {
        id: 'CHP-5307-6784-3140',
        revision: 14,
        chat: {
          id: 'CHT-9231-8917-3633',
          name: 'Mobile Dev Test Chat - Group One',
          revision: 2,
          type: 'Group',
        },
        contact: {
          id: 'CTT-4262-4296',
          name: 'Tania Roche',
          revision: 1,
          email: 'tania.roche@softwareone.com',
          identity: {
            id: 'USR-2267-7838',
            name: 'Tania Roche',
            revision: 1,
          },
        },
        identity: {
          id: 'USR-2267-7838',
          name: 'Tania Roche',
          revision: 1,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        lastReadMessage: {
          id: 'CMG-1083-9603-6187',
          revision: 1,
          content: 'test for recent message',
          visibility: 'Public',
          isDeleted: false,
        },
        unreadMessageCount: 0,
      },
      {
        id: 'CHP-5576-4281-4209',
        revision: 1,
        chat: {
          id: 'CHT-9231-8917-3633',
          name: 'Mobile Dev Test Chat - Group One',
          revision: 2,
          type: 'Group',
        },
        contact: {
          id: 'CTT-5591-7535',
          name: 'Magdalena Komuda',
          revision: 1,
          email: 'Magdalena.Komuda@softwareone.com',
          identity: {
            id: 'USR-8905-2920',
            name: 'Magdalena Komuda',
            revision: 1,
          },
        },
        identity: {
          id: 'USR-8905-2920',
          name: 'Magdalena Komuda',
          revision: 1,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        unreadMessageCount: 6,
      },
      {
        id: 'CHP-6078-8516-3871',
        revision: 1,
        chat: {
          id: 'CHT-9231-8917-3633',
          name: 'Mobile Dev Test Chat - Group One',
          revision: 2,
          type: 'Group',
        },
        contact: {
          id: 'CTT-8104-3524',
          name: 'Balint Polgar',
          revision: 1,
          email: 'balint.polgar@softwareone.com',
          identity: {
            id: 'USR-0556-8733',
            name: 'Balint Polgar',
            icon: '/v1/accounts/users/USR-0556-8733/icon',
            revision: 18,
          },
        },
        identity: {
          id: 'USR-0556-8733',
          name: 'Balint Polgar',
          icon: '/v1/accounts/users/USR-0556-8733/icon',
          revision: 18,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        unreadMessageCount: 6,
      },
      {
        id: 'CHP-8092-8347-2652',
        revision: 16,
        chat: {
          id: 'CHT-9231-8917-3633',
          name: 'Mobile Dev Test Chat - Group One',
          revision: 2,
          type: 'Group',
        },
        contact: {
          id: 'CTT-4634-2964',
          name: 'MIchal Walczak',
          revision: 1,
          email: 'michal.walczak@softwareone.com',
          identity: {
            id: 'USR-2022-1452',
            name: 'Michal Walczak',
            icon: '/v1/accounts/users/USR-2022-1452/icon',
            revision: 26,
          },
        },
        identity: {
          id: 'USR-2022-1452',
          name: 'Michal Walczak',
          icon: '/v1/accounts/users/USR-2022-1452/icon',
          revision: 26,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        lastReadMessage: {
          id: 'CMG-1083-9603-6187',
          revision: 1,
          content: 'test for recent message',
          visibility: 'Public',
          isDeleted: false,
        },
        unreadMessageCount: 0,
      },
    ],
    lastMessage: {
      id: 'CMG-1083-9603-6187',
      revision: 1,
      chat: {
        id: 'CHT-9231-8917-3633',
        name: 'Mobile Dev Test Chat - Group One',
        revision: 2,
        type: 'Group',
      },
      sender: {
        id: 'CHP-5307-6784-3140',
        revision: 14,
        chat: {
          id: 'CHT-9231-8917-3633',
          name: 'Mobile Dev Test Chat - Group One',
          revision: 2,
          type: 'Group',
        },
        contact: {
          id: 'CTT-4262-4296',
          name: 'Tania Roche',
          revision: 1,
          email: 'tania.roche@softwareone.com',
          identity: {
            id: 'USR-2267-7838',
            name: 'Tania Roche',
            revision: 1,
          },
        },
        identity: {
          id: 'USR-2267-7838',
          name: 'Tania Roche',
          revision: 1,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        lastReadMessage: {
          id: 'CMG-1083-9603-6187',
          revision: 1,
          content: 'test for recent message',
          visibility: 'Public',
          isDeleted: false,
        },
        unreadMessageCount: 0,
      },
      content: 'test for recent message',
      visibility: 'Public',
      isDeleted: false,
      identity: {
        id: 'USR-2267-7838',
        name: 'Tania Roche',
        revision: 1,
      },
      audit: {
        deleted: {},
        madePublic: {},
        madePrivate: {},
        created: {
          at: '2026-02-09T10:50:26.430Z',
          by: {
            id: 'USR-2267-7838',
            name: 'Tania Roche',
            revision: 1,
          },
        },
        updated: {},
      },
    },
  },
  {
    id: 'CHT-4253-7222-5702',
    revision: 1,
    type: 'Direct',
    participants: [
      {
        id: 'CHP-4768-7226-5802',
        revision: 9,
        chat: {
          id: 'CHT-4253-7222-5702',
          revision: 1,
          type: 'Direct',
        },
        contact: {
          id: 'CTT-4634-2964',
          name: 'MIchal Walczak',
          revision: 1,
          email: 'michal.walczak@softwareone.com',
          identity: {
            id: 'USR-2022-1452',
            name: 'Michal Walczak',
            icon: '/v1/accounts/users/USR-2022-1452/icon',
            revision: 26,
          },
        },
        identity: {
          id: 'USR-2022-1452',
          name: 'Michal Walczak',
          icon: '/v1/accounts/users/USR-2022-1452/icon',
          revision: 26,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        lastReadMessage: {
          id: 'CMG-4912-0427-1898',
          revision: 1,
          content: 'You should be able to see that chat, as I have invited you too',
          visibility: 'Public',
          isDeleted: false,
        },
        unreadMessageCount: 1,
      },
      {
        id: 'CHP-6694-2147-1686',
        revision: 17,
        chat: {
          id: 'CHT-4253-7222-5702',
          revision: 1,
          type: 'Direct',
        },
        contact: {
          id: 'CTT-4262-4296',
          name: 'Tania Roche',
          revision: 1,
          email: 'tania.roche@softwareone.com',
          identity: {
            id: 'USR-2267-7838',
            name: 'Tania Roche',
            revision: 1,
          },
        },
        identity: {
          id: 'USR-2267-7838',
          name: 'Tania Roche',
          revision: 1,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        lastReadMessage: {
          id: 'CMG-4348-8387-0436',
          revision: 1,
          content: 'update test',
          visibility: 'Public',
          isDeleted: false,
        },
        unreadMessageCount: 100,
      },
    ],
    lastMessage: {
      id: 'CMG-4348-8387-0436',
      revision: 1,
      chat: {
        id: 'CHT-4253-7222-5702',
        revision: 1,
        type: 'Direct',
      },
      sender: {
        id: 'CHP-6694-2147-1686',
        revision: 17,
        chat: {
          id: 'CHT-4253-7222-5702',
          revision: 1,
          type: 'Direct',
        },
        contact: {
          id: 'CTT-4262-4296',
          name: 'Tania Roche',
          revision: 1,
          email: 'tania.roche@softwareone.com',
          identity: {
            id: 'USR-2267-7838',
            name: 'Tania Roche',
            revision: 1,
          },
        },
        identity: {
          id: 'USR-2267-7838',
          name: 'Tania Roche',
          revision: 1,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        lastReadMessage: {
          id: 'CMG-4348-8387-0436',
          revision: 1,
          content: 'update test',
          visibility: 'Public',
          isDeleted: false,
        },
        unreadMessageCount: 0,
      },
      content: 'update test',
      visibility: 'Public',
      isDeleted: false,
      identity: {
        id: 'USR-2267-7838',
        name: 'Tania Roche',
        revision: 1,
      },
      audit: {
        deleted: {},
        madePublic: {},
        madePrivate: {},
        created: {
          at: '2025-03-09T10:46:50.968Z',
          by: {
            id: 'USR-2267-7838',
            name: 'Tania Roche',
            revision: 1,
          },
        },
        updated: {},
      },
    },
  },
  {
    id: 'CHT-3390-6074-5983',
    revision: 1,
    type: 'Direct',
    participants: [
      {
        id: 'CHP-1678-4601-5308',
        revision: 1,
        chat: {
          id: 'CHT-3390-6074-5983',
          revision: 1,
          type: 'Direct',
        },
        contact: {
          id: 'CTT-4262-4296',
          name: 'Tania Roche',
          revision: 1,
          email: 'tania.roche@softwareone.com',
          identity: {
            id: 'USR-2267-7838',
            name: 'Tania Roche',
            revision: 1,
          },
        },
        identity: {
          id: 'USR-2267-7838',
          name: 'Tania Roche',
          revision: 1,
        },
        account: {
          id: 'ACC-1032-0145',
          name: 'SoftwareOne',
          icon: '/v1/accounts/accounts/ACC-1032-0145/icon',
          revision: 4,
          type: 'Operations',
          status: 'Enabled',
        },
        muted: false,
        status: 'Active',
        unreadMessageCount: 0,
      },
      {
        id: 'CHP-5456-0462-7816',
        revision: 1,
        chat: {
          id: 'CHT-3390-6074-5983',
          revision: 1,
          type: 'Direct',
        },
        contact: {
          id: 'CTT-0869-8652',
          name: 'Maciej Biernat',
          revision: 1,
          email: 'maciej.biernat@softwareone.com',
          identity: {
            id: 'USR-1835-2941',
            name: 'Maciej Biernat',
            icon: '/v1/accounts/users/USR-1835-2941/icon',
            revision: 8,
          },
        },
        identity: {
          id: 'USR-1835-2941',
          name: 'Maciej Biernat',
          icon: '/v1/accounts/users/USR-1835-2941/icon',
          revision: 8,
        },
        account: {
          id: 'ACC-1360-4582',
          name: 'Adastra',
          icon: '/v1/accounts/accounts/ACC-1360-4582/icon',
          revision: 1,
          type: 'Client',
          status: 'Active',
        },
        muted: false,
        status: 'Active',
        unreadMessageCount: 0,
      },
    ],
  },
];
