export const DEFAULT_PAGE_SIZE = 50;
export const DEFAULT_OFFSET = 0;

export const DEFAULT_SPOTLIGHT_LIMIT = 100;

export const MAX_RECENT_ACCOUNTS = 10;

export const FLATLIST_END_REACHED_THRESHOLD = 0.6;

export const AUTH0_REQUEST_TIMEOUT_MS = 20000;
export const AUTH0_REFRESH_TOKEN_MAX_RETRIES = 5;
export const AUTH0_REFRESH_TOKEN_INITIAL_DELAY_MS = 1000;
