import {
  SpotlightScreen,
  OrdersScreen,
  SubscriptionsScreen,
  AgreementsScreen,
  InvoicesScreen,
  CreditMemosScreen,
  JournalsScreen,
  StatementsScreen,
  UsersScreen,
  UserAccountsScreen,
  ProgramsScreen,
  EnrollmentsScreen,
  LicenseesScreen,
  BuyersScreen,
  ClientsScreen,
  VendorsScreen,
  SellersScreen,
  ProductsScreen,
  CreditMemoDetailsScreen,
  JournalDetailsScreen,
  OrderDetailsScreen,
  AccountDetailsScreen,
  UserDetailsScreen,
  BuyerDetailsScreen,
  SellerDetailsScreen,
  AgreementDetailsScreen,
  LicenseeDetailsScreen,
  SubscriptionDetailsScreen,
  InvoiceDetailsScreen,
  StatementDetailsScreen,
  ProductDetailsScreen,
  ProgramDetailsScreen,
  EnrollmentDetailsScreen,
  CertificateDetailsScreen,
  ChatScreen,
  ChatConversationScreen,
  CertificatesScreen,
  SearchScreen,
} from '@/screens';
import type {
  MainTabItem,
  SecondaryTabGroup,
  SecondaryTabItem,
  AppScreenItem,
} from '@/types/navigation';

export const TAB_BAR_CONTENT_HEIGHT = 65;

export const mainTabsData: MainTabItem[] = [
  { name: 'spotlight', icon: 'flare', component: SpotlightScreen, stackRootName: 'spotlightRoot' },
  {
    name: 'search',
    icon: 'search',
    component: SearchScreen,
    stackRootName: 'searchRoot',
  },
  {
    name: 'chat',
    icon: 'chat-bubble',
    component: ChatScreen,
    stackRootName: 'chatRoot',
  },
  { name: 'more', icon: 'more-horiz', stackRootName: 'moreRoot' },
];

export const secondaryTabsData: SecondaryTabGroup[] = [
  {
    title: 'administration',
    items: [
      {
        name: 'allBuyers',
        icon: 'shopping-cart-checkout',
        component: BuyersScreen,
        modules: ['platform-account-management'],
        roles: ['Operations'],
      },
      {
        name: 'clients',
        icon: 'contacts',
        component: ClientsScreen,
        modules: ['platform-account-management'],
        roles: ['Operations'],
      },
      {
        name: 'allUsers',
        icon: 'group',
        component: UsersScreen,
        modules: ['platform-account-management'],
        roles: ['Operations'],
      },
      {
        name: 'vendors',
        icon: 'storefront',
        component: VendorsScreen,
        modules: ['platform-account-management'],
        roles: ['Operations'],
      },
      {
        name: 'sellers',
        icon: 'public',
        component: SellersScreen,
        modules: ['platform-account-management'],
        roles: ['Operations'],
      },
    ],
  },
  {
    title: 'billing',
    items: [
      {
        name: 'creditMemos',
        icon: 'credit-card',
        component: CreditMemosScreen,
        modules: ['billing'],
        roles: ['Client', 'Operations'],
      },
      {
        name: 'invoices',
        icon: 'receipt-long',
        component: InvoicesScreen,
        modules: ['billing'],
        roles: ['Client', 'Operations'],
      },
      {
        name: 'journals',
        icon: 'menu-book',
        component: JournalsScreen,
        modules: ['billing'],
        roles: ['Vendor', 'Operations'],
      },
      {
        name: 'statements',
        icon: 'receipt',
        component: StatementsScreen,
        modules: ['billing'],
        roles: ['Client', 'Operations'],
      },
    ],
  },
  {
    title: 'catalog',
    items: [
      {
        name: 'products',
        icon: 'inventory-2',
        component: ProductsScreen,
        modules: ['catalog-management'],
        roles: ['Vendor', 'Operations'],
      },
      {
        name: 'products',
        icon: 'inventory-2',
        component: ProductsScreen,
        modules: ['new-marketplace'],
        roles: ['Client'],
      },
    ],
  },
  {
    title: 'marketplace',
    items: [
      {
        name: 'agreements',
        icon: 'fact-check',
        component: AgreementsScreen,
        modules: ['new-marketplace'],
        roles: ['Client', 'Vendor', 'Operations'],
      },
      {
        name: 'orders',
        icon: 'shopping-cart',
        component: OrdersScreen,
        modules: ['new-marketplace'],
        roles: ['Client', 'Vendor', 'Operations'],
      },
      {
        name: 'subscriptions',
        icon: 'subscriptions',
        component: SubscriptionsScreen,
        modules: ['new-marketplace'],
        roles: ['Client', 'Vendor', 'Operations'],
      },
    ],
  },
  {
    title: 'program',
    items: [
      {
        name: 'certificates',
        icon: 'workspace-premium',
        component: CertificatesScreen,
        modules: ['new-marketplace'],
        roles: ['Client'],
      },
      {
        name: 'certificates',
        icon: 'workspace-premium',
        component: CertificatesScreen,
        modules: ['catalog-management'],
        roles: ['Vendor', 'Operations'],
      },
      {
        name: 'enrollments',
        icon: 'badge',
        component: EnrollmentsScreen,
        modules: ['new-marketplace'],
        roles: ['Client', 'Vendor', 'Operations'],
      },
      {
        name: 'programs',
        icon: 'redeem',
        component: ProgramsScreen,
        modules: ['new-marketplace'],
        roles: ['Client', 'Vendor', 'Operations'],
      },
    ],
  },
  {
    title: 'settings',
    items: [
      {
        name: 'buyers',
        icon: 'shopping-cart-checkout',
        component: BuyersScreen,
        modules: ['account-management'],
        roles: ['Client'],
      },
      {
        name: 'sellers',
        icon: 'public',
        component: SellersScreen,
        modules: ['account-management'],
        roles: ['Client'],
      },
      {
        name: 'users',
        icon: 'group',
        component: UsersScreen,
        modules: ['access-management'],
        roles: ['Client', 'Vendor', 'Operations'],
      },
    ],
  },
];

export const secondaryTabItems: SecondaryTabItem[] = secondaryTabsData.flatMap(
  (section) => section.items,
);

export const appScreensData: AppScreenItem[] = [
  { name: 'agreements', component: AgreementsScreen },
  { name: 'creditMemos', component: CreditMemosScreen },
  { name: 'journals', component: JournalsScreen },
  { name: 'invoices', component: InvoicesScreen },
  { name: 'statements', component: StatementsScreen },
  { name: 'users', component: UsersScreen },
  { name: 'accounts', component: UserAccountsScreen },
  { name: 'allUsers', component: UsersScreen },
  { name: 'programs', component: ProgramsScreen },
  { name: 'enrollments', component: EnrollmentsScreen },
  { name: 'certificates', component: CertificatesScreen },
  { name: 'licensees', component: LicenseesScreen },
  { name: 'buyers', component: BuyersScreen },
  { name: 'allBuyers', component: BuyersScreen },
  { name: 'clients', component: ClientsScreen },
  { name: 'vendors', component: VendorsScreen },
  { name: 'sellers', component: SellersScreen },
  { name: 'products', component: ProductsScreen },
  { name: 'orders', component: OrdersScreen },
  { name: 'subscriptions', component: SubscriptionsScreen },
  { name: 'creditMemoDetails', component: CreditMemoDetailsScreen },
  { name: 'journalDetails', component: JournalDetailsScreen },
  { name: 'orderDetails', component: OrderDetailsScreen },
  { name: 'accountDetails', component: AccountDetailsScreen },
  { name: 'userDetails', component: UserDetailsScreen },
  { name: 'buyerDetails', component: BuyerDetailsScreen },
  { name: 'sellerDetails', component: SellerDetailsScreen },
  { name: 'agreementDetails', component: AgreementDetailsScreen },
  { name: 'licenseeDetails', component: LicenseeDetailsScreen },
  { name: 'subscriptionDetails', component: SubscriptionDetailsScreen },
  { name: 'invoiceDetails', component: InvoiceDetailsScreen },
  { name: 'statementDetails', component: StatementDetailsScreen },
  { name: 'productDetails', component: ProductDetailsScreen },
  { name: 'programDetails', component: ProgramDetailsScreen },
  { name: 'enrollmentDetails', component: EnrollmentDetailsScreen },
  { name: 'certificateDetails', component: CertificateDetailsScreen },
  { name: 'chatConversation', component: ChatConversationScreen },
];
