name: 'iOS Appium Testing'
description: 'Setup and run Appium tests on iOS simulator'
inputs:
  device_uuid:
    description: 'iOS simulator device UUID'
    required: true
  device_name:
    description: 'iOS simulator device name'
    required: false
    default: 'iPhone 16'
  ios_version:
    description: 'iOS version'
    required: false
    default: '26.0'
  node_version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  appium_version:
    description: 'Appium version to install'
    required: false
    default: '3.1.1'
  app_bundle_id:
    description: 'iOS app bundle identifier'
    required: true
  appium_host:
    description: 'Appium server host'
    required: false
    default: 'localhost'
  appium_port:
    description: 'Appium server port'
    required: false
    default: '4723'

runs:
  using: 'composite'
  steps:
    - name: Verify Required Inputs
      shell: bash
      run: |
        echo "🔍 Verifying required inputs..."
        
        # Check required inputs
        if [ -z "${{ inputs.app_bundle_id }}" ]; then
          echo "❌ ERROR: app_bundle_id input is required"
          exit 1
        else
          echo "✅ app_bundle_id is set"
        fi
        
        # Check optional inputs (show defaults if not set)
        if [ -z "${{ inputs.appium_host }}" ]; then
          echo "ℹ️  appium_host not set, using default: localhost"
        else
          echo "✅ appium_host is set"
        fi
        
        if [ -z "${{ inputs.appium_port }}" ]; then
          echo "ℹ️  appium_port not set, using default: 4723"
        else
          echo "✅ appium_port is set"
        fi
        
        # Verify required inputs
        if [ -z "${{ inputs.device_uuid }}" ]; then
          echo "❌ ERROR: device_uuid input is required"
          exit 1
        else
          echo "✅ device_uuid input is provided: ${{ inputs.device_uuid }}"
        fi
        
        echo "🎉 All required inputs are properly configured!"

    - name: Checkout test repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'
        cache-dependency-path: app/package-lock.json

    - name: Restore node modules cache
      id: npm-cache
      uses: actions/cache@v4
      with:
        path: |
          app/node_modules
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('app/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies (only missing packages)
      shell: bash
      run: npm ci
      working-directory: ./app

    - name: Install Appium
      shell: bash
      run: |
        npm install -g appium@${{ inputs.appium_version }}
        appium --version
        
    - name: Install Appium XCUITest driver
      shell: bash
      run: |
        appium driver install xcuitest || echo "Driver already installed"
        appium driver list --installed
        
    - name: Pre-build WebDriverAgent for CI
      shell: bash
      env:
        DEVICE_UDID: ${{ inputs.device_uuid }}
      run: |
        echo "🔧 Pre-building WebDriverAgent to avoid CI connection issues..."
        
        # Get WebDriverAgent path
        WDA_PATH=$(find ~/.appium/node_modules -name "WebDriverAgent.xcodeproj" 2>/dev/null | head -1)
        
        if [ -n "$WDA_PATH" ]; then
          echo "📁 Found WebDriverAgent at: $WDA_PATH"
          WDA_DIR=$(dirname "$WDA_PATH")
          
          # Pre-build WebDriverAgent for the target simulator
          echo "🔨 Building WebDriverAgent for simulator..."
          cd "$WDA_DIR"
          
          xcodebuild build-for-testing \
            -project WebDriverAgent.xcodeproj \
            -scheme WebDriverAgentRunner \
            -destination "platform=iOS Simulator,id=${{ env.DEVICE_UDID }}" \
            -derivedDataPath /tmp/wda-derived-data \
            -quiet || echo "⚠️ WebDriverAgent pre-build failed, continuing anyway"
          
          echo "✅ WebDriverAgent pre-build completed"
        else
          echo "⚠️ WebDriverAgent not found, skipping pre-build"
        fi

    - name: Prepare simulator for XCUITest
      shell: bash
      env:
        DEVICE_UDID: ${{ inputs.device_uuid }}
        APP_BUNDLE_ID: ${{ inputs.app_bundle_id }}
      run: |
        echo "🔍 Preparing simulator for XCUITest in CI environment..."
        
        # Check simulator status
        SIMULATOR_STATUS=$(xcrun simctl list devices | grep "${{ env.DEVICE_UDID }}" | head -1 || echo "Not found")
        echo "Initial simulator status: $SIMULATOR_STATUS"
        
        if ! echo "$SIMULATOR_STATUS" | grep -q "(Booted)"; then
          echo "❌ ERROR: Simulator is not booted. Install workflow should have prepared this."
          echo "Expected simulator to be ready from previous workflow step."
          exit 1
        fi
        
        # CI-specific: Reset simulator state for clean XCUITest connection
        echo "🔄 Resetting simulator state for XCUITest..."
        xcrun simctl shutdown "${{ env.DEVICE_UDID }}" || true
        sleep 3
        
        echo "🚀 Booting simulator with fresh state..."
        xcrun simctl boot "${{ env.DEVICE_UDID }}"
        
        # Wait for simulator to be fully ready - use multiple readiness indicators
        echo "⏳ Waiting for simulator to be fully operational..."
        WAIT_COUNT=0
        MAX_WAIT=30
        BOOT_READY=false
        
        while [ $WAIT_COUNT -lt $MAX_WAIT ]; do
          # Check if simulator is booted (primary indicator)
          SIMULATOR_STATUS=$(xcrun simctl list devices | grep "${{ env.DEVICE_UDID }}" | head -1 || echo "Not found")
          if echo "$SIMULATOR_STATUS" | grep -q "(Booted)"; then
            echo "✅ Simulator is booted"
            
            # Try boot status check with timeout - if it hangs, skip it
            echo "🔍 Checking boot status readiness (with timeout)..."
            if timeout 5 xcrun simctl bootstatus "${{ env.DEVICE_UDID }}" 2>/dev/null | grep -q "Boot status is ready" 2>/dev/null; then
              echo "✅ Simulator boot status is ready"
              BOOT_READY=true
              break
            elif [ $? -eq 124 ]; then
              echo "⚠️ Boot status check timed out (5s), but simulator is booted - proceeding"
              BOOT_READY=true
              break
            else
              echo "📱 Simulator booted but boot status not ready yet, waiting..."
            fi
          else
            echo "⏳ Simulator not yet booted, waiting... (${WAIT_COUNT}/${MAX_WAIT})"
          fi
          
          sleep 2
          WAIT_COUNT=$((WAIT_COUNT + 1))
        done
        
        if [ "$BOOT_READY" = false ]; then
          if [ $WAIT_COUNT -eq $MAX_WAIT ]; then
            echo "⚠️ WARNING: Simulator readiness check timed out, but proceeding anyway"
          else
            echo "⚠️ WARNING: Could not verify simulator readiness, but proceeding anyway"
          fi
        fi
        
        # Additional delay for UI services to stabilize
        echo "⏳ Allowing UI services to stabilize..."
        sleep 5
        
        # CI-specific: Ensure Simulator UI is visible for WebDriverAgent
        echo "📺 Ensuring Simulator UI is visible for WebDriverAgent..."
        open -a Simulator.app --args -CurrentDeviceUDID "${{ env.DEVICE_UDID }}" || true
        sleep 3
        
        # Verify simulator UI is properly visible
        echo "🔍 Verifying Simulator UI state..."
        if pgrep -f "Simulator.app" > /dev/null; then
          echo "✅ Simulator UI is running"
        else
          echo "⚠️ WARNING: Simulator UI may not be visible"
        fi
        
        # Verify app is still installed after reset
        if xcrun simctl listapps "${{ env.DEVICE_UDID }}" 2>/dev/null | grep -q "${{ env.APP_BUNDLE_ID }}"; then
          echo "✅ App is installed and ready"
        else
          echo "⚠️ WARNING: Could not verify app installation, but proceeding with test"
          echo "Appium will provide better error messages if app is missing"
        fi
        
        echo "🎯 Simulator is prepared for XCUITest"
        
    - name: Start Appium Server
      shell: bash
      env:
        APPIUM_HOST: ${{ inputs.appium_host }}
        APPIUM_PORT: ${{ inputs.appium_port }}
      run: |
        echo "Starting Appium server..."
        appium --log-level info --log appium.log &
        APPIUM_PID=$!
        echo ${APPIUM_PID} > appium.pid
        echo "Appium PID: ${APPIUM_PID}"
        
        # Wait for Appium to start
        APPIUM_WAIT_SECONDS=65
        echo "Waiting for Appium server to start (timeout: ${APPIUM_WAIT_SECONDS}s)..."
        for i in $(seq 1 ${APPIUM_WAIT_SECONDS}); do
          if curl -s "http://${APPIUM_HOST}:${APPIUM_PORT}/status" > /dev/null; then
            echo "✓ Appium server is ready"
            break
          fi
          if [ $i -eq ${APPIUM_WAIT_SECONDS} ]; then
            echo "✗ Appium server failed to start within ${APPIUM_WAIT_SECONDS} seconds"
            cat appium.log
            exit 1
          fi
          echo "Waiting... ($i/${APPIUM_WAIT_SECONDS})"
          sleep 1
        done
        
        # Extract working URLs from Appium logs for WebDriver connection
        echo "🔍 Extracting Appium connection URLs from logs..."
        NETWORK_URL=$(grep -E "http://[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:${APPIUM_PORT}/" appium.log | head -1 | sed 's/.*\(http:\/\/[0-9\.]*:[0-9]*\)\/.*/\1/')
        LOCALHOST_URL="http://127.0.0.1:${APPIUM_PORT}"
        
        if [ -n "$NETWORK_URL" ]; then
          echo "✅ Found network URL: $NETWORK_URL"
          echo "VERIFIED_APPIUM_URL=$NETWORK_URL" >> $GITHUB_ENV
        else
          echo "⚠️ Network URL not found, using localhost"
          echo "VERIFIED_APPIUM_URL=$LOCALHOST_URL" >> $GITHUB_ENV
        fi
        
        echo "📋 Available Appium URLs for WebDriver:"
        echo "  - Localhost: $LOCALHOST_URL"
        [ -n "$NETWORK_URL" ] && echo "  - Network: $NETWORK_URL"
        
    - name: Verify Appium Server
      shell: bash
      env:
        APPIUM_HOST: ${{ inputs.appium_host }}
        APPIUM_PORT: ${{ inputs.appium_port }}
      run: |
        echo "Verifying Appium server status..."
        curl -f "http://${APPIUM_HOST}:${APPIUM_PORT}/status" | jq '.'

    - name: Pre-test Debug Information
      shell: bash
      env:
        DEVICE_UDID: ${{ inputs.device_uuid }}
        DEVICE_NAME: ${{ inputs.device_name }}
        PLATFORM_VERSION: ${{ inputs.ios_version }}
        APP_BUNDLE_ID: ${{ inputs.app_bundle_id }}
        APPIUM_HOST: ${{ inputs.appium_host }}
        APPIUM_PORT: ${{ inputs.appium_port }}
      run: |
        echo "=== Pre-test Debug Information ==="
        echo "Environment Variables:"
        echo "DEVICE_UDID: ${{ env.DEVICE_UDID }}"
        echo "DEVICE_NAME: ${{ env.DEVICE_NAME }}"
        echo "PLATFORM_VERSION: ${{ env.PLATFORM_VERSION }}"
        echo "APP_BUNDLE_ID: ${{ env.APP_BUNDLE_ID }}"
        echo "APPIUM_HOST: ${{ env.APPIUM_HOST }}"
        echo "APPIUM_PORT: ${{ env.APPIUM_PORT }}"
        echo "VERIFIED_APPIUM_URL: ${VERIFIED_APPIUM_URL:-'Not set'}"
        
        echo "Current Simulator Status:"
        xcrun simctl list devices | grep "${{ env.DEVICE_UDID }}" || echo "Device not found"
        
        echo "App Installation Status:"
        if xcrun simctl list devices | grep "${{ env.DEVICE_UDID }}" | grep -q "(Booted)"; then
          xcrun simctl listapps ${{ env.DEVICE_UDID }} | grep -i "${{ env.APP_BUNDLE_ID }}" || echo "App not found"
        else
          echo "Cannot check app status - simulator not booted"
        fi
        
        echo "Appium Server Status Check:"
        echo "  Testing default URL: http://${{ env.APPIUM_HOST }}:${{ env.APPIUM_PORT }}/status"
        curl -s "http://${{ env.APPIUM_HOST }}:${{ env.APPIUM_PORT }}/status" | jq '.' || echo "Default URL not reachable"
        
        if [ -n "$VERIFIED_APPIUM_URL" ]; then
          echo "  Testing verified URL: ${VERIFIED_APPIUM_URL}/status"
          curl -s "${VERIFIED_APPIUM_URL}/status" | jq '.' || echo "Verified URL not reachable"
        fi
        
    - name: Run Appium Tests
      shell: bash
      working-directory: ./app
      continue-on-error: false
      env:
        DEVICE_UDID: ${{ inputs.device_uuid }}
        DEVICE_NAME: ${{ inputs.device_name }}
        PLATFORM_VERSION: ${{ inputs.ios_version }}
        APP_BUNDLE_ID: ${{ inputs.app_bundle_id }}
      run: |
        echo "🚀 Starting WebDriver tests with verified Appium connection..."
        
        # Priority: Use verified network URL if available, otherwise use input values
        if [ -n "$VERIFIED_APPIUM_URL" ]; then
          EXTRACTED_HOST=$(echo "$VERIFIED_APPIUM_URL" | sed 's|http://\([^:]*\):.*|\1|')
          EXTRACTED_PORT=$(echo "$VERIFIED_APPIUM_URL" | sed 's|.*:\([0-9]*\)|\1|')
          
          echo "📡 Using verified network connection: $VERIFIED_APPIUM_URL"
          echo "   Host: $EXTRACTED_HOST"
          echo "   Port: $EXTRACTED_PORT"
          
          export APPIUM_HOST="$EXTRACTED_HOST"
          export APPIUM_PORT="$EXTRACTED_PORT"
        else
          # Fall back to input values
          export APPIUM_HOST="${{ inputs.appium_host }}"
          export APPIUM_PORT="${{ inputs.appium_port }}"
          echo "⚠️  Using input values: http://$APPIUM_HOST:$APPIUM_PORT"
        fi
        
        # Test the connection before running tests
        echo "🔧 Testing WebDriver connection..."
        WEBDRIVER_URL="http://${APPIUM_HOST}:${APPIUM_PORT}"
        if curl -s "$WEBDRIVER_URL/status" > /dev/null; then
          echo "✅ WebDriver connection test successful: $WEBDRIVER_URL"
        else
          echo "❌ WebDriver connection test failed: $WEBDRIVER_URL"
          echo "Trying localhost fallback..."
          export APPIUM_HOST="localhost"
          if curl -s "http://localhost:${APPIUM_PORT}/status" > /dev/null; then
            echo "✅ Localhost fallback successful"
          else
            echo "❌ All connection attempts failed"
            exit 1
          fi
        fi
        
        echo "🎯 Running tests with APPIUM_HOST=$APPIUM_HOST APPIUM_PORT=$APPIUM_PORT"
        echo "📋 WebDriverIO Environment Variables:"
        echo "   DEVICE_UDID: $DEVICE_UDID"
        echo "   DEVICE_NAME: $DEVICE_NAME"
        echo "   PLATFORM_VERSION: $PLATFORM_VERSION"
        echo "   APP_BUNDLE_ID: $APP_BUNDLE_ID"
        echo "   APPIUM_HOST: $APPIUM_HOST"
        echo "   APPIUM_PORT: $APPIUM_PORT"
        npx wdio run wdio.conf.js --suite welcome
        
    - name: Upload Appium logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: appium-logs-${{ github.run_number }}
        path: appium.log
        retention-days: 7
        if-no-files-found: warn
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ github.run_number }}
        path: |
          app/test-results/
          app/screenshots/
        retention-days: 7
        if-no-files-found: ignore
        
    - name: Capture simulator logs
      if: always()
      shell: bash
      env:
        DEVICE_UDID: ${{ inputs.device_uuid }}
      run: |
        echo "Capturing simulator logs..."
        xcrun simctl spawn ${{ env.DEVICE_UDID }} log collect --output simulator.log || true
        
    - name: Upload simulator logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: simulator-logs-${{ github.run_number }}
        path: simulator.log
        retention-days: 7
        if-no-files-found: ignore
        
    - name: Shutdown Simulator
      if: always()
      shell: bash
      env:
        DEVICE_UDID: ${{ inputs.device_uuid }}
      run: |
        echo "Shutting down simulator..."
        xcrun simctl shutdown ${{ env.DEVICE_UDID }} || true
        echo "✓ Simulator shutdown complete"
        
    - name: Stop Appium Server
      if: always()
      shell: bash
      run: |
        if [ -f appium.pid ]; then
          APPIUM_PID=$(cat appium.pid)
          echo "Stopping Appium server (PID: ${APPIUM_PID})..."
          kill ${APPIUM_PID} || true
          rm appium.pid
          echo "✓ Appium server stopped"
        fi
        
    - name: Cleanup
      if: always()
      shell: bash
      env:
        DEVICE_UDID: ${{ inputs.device_uuid }}
        APP_BUNDLE_ID: ${{ inputs.app_bundle_id }}
      run: |
        echo "Cleaning up test artifacts..."
        # Optional: Remove app from simulator
        # xcrun simctl uninstall ${{ env.DEVICE_UDID }} ${{ env.APP_BUNDLE_ID }} || true
        echo "✓ Cleanup complete"